### ISSUE TITLE
LSPS2 - Tracking Issue

### ISSUE THREAD

**Issue by ErikDeSmedt** [Blockstream/greenlight#258]
This is a tracking issue for a minimum viable implementation of the LSPS2 specification.
Greenlight will only implement the client-side and assume the LSPS trusts client flow.

** Preparation **
- [ ]  Discovery of LSP-servers

** LSP-2 parts**
- [ ]  lsps2.get_versions
- [ ] lsps2.get_info
- [ ] lsps2.buy
- [ ] First invoice generation using the scid received from lsps.buy
- [ ] Claiming the first payment
- [ ] Stop execution on Client trusts LSPS flow by default. 
- [ ]  Create warning if LSP closes channels to early
